### ISSUE TITLE
POSIX compliance

### ISSUE THREAD

**Issue by argosopentech** [argosopentech/LibreTranslate-sh#2]
I merged this commit for POSIX compliance months ago and I'm considering reverting it. I don't really understand the syntax it is using.
https://github.com/argosopentech/LibreTranslate-sh/commit/75a96fd0bbae5cdb73cfd8fe8c4bf4235f0090b4

Does anyone have insight into the best way to be POSIX compliant?

**Comment by pierotofy** [comment]
You can use `shellcheck`: https://www.baeldung.com/linux/test-posix-compliance-shell-scripts#checking-posix-compliance-with-shellcheck

**Comment by argosopentech** [comment]
Reverted
